services:
  postgres:
    image: postgres:18-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  payment_service:
    build: .
    image: payment_service
    container_name: payment_service
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./payment_service:/app/www/payment_service
    ports:
        - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres-data: